### ISSUE TITLE
when installed, to modify a resource I can not access template variables

### ISSUE THREAD

**Issue by NtcRLoaD** [Sterc/mapsTv#7] opened 2015-03-09 18:11 UTC
When installed, to modify a resource I can not access template variables

Title change for "undefined"

Modx: modx-2.3.3
PHP: 5.2
![undefined](https://cloud.githubusercontent.com/assets/11394619/6561224/7ede9896-c65d-11e4-93d3-ce511d326f51.png)

**Comment by Bumme** [comment] 2015-07-06 10:44
Do you still have this problem?

**Comment by MrRoco** [comment] 2015-11-27 07:59
Tested in later releases, can't reproduce the issue. 

Closing it

**Closed by MrRoco** 2015-11-27 07:59 UTC
